config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#my_portfolio'
  get 'my_portfolio', to: "users#my_portfolio"
  get 'search_stock', to: "stocks#search_stock"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  def self.lookup(ticker_sym)
    client = Clients::StockClient.new
    begin
      price = client.price(ticker_sym)
      company_name = client.company_name(ticker_sym)
      return new(ticker: ticker_sym, name: company_name, last_price: price)
    rescue => exception
      return nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search_stock
    @stock = Stock.lookup(params[:stock])
    if params[:stock].present?
      if @stock
        render partial: "users/result"
      else
        flash.now[:alert] = "Stock not found"
        render partial: "users/result"
      end
    else 
      flash.now[:alert] = "Stock is empty"
      render partial: "users/result"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
    <h4 class="alert-heading"><%= notice %></h4>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
    <h4 class="alert-heading"><%= alert %></h4>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_result.html.erb
<%= render "layouts/messages" %>

<% if @stock %>
  <div class="card card-header result-card">
    <strong>Stock:</strong> <%= @stock.ticker %>,
    <strong>Company name:</strong> <%= @stock.name %>,
    <strong>Last Price:</strong> <%= @stock.last_price %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector("#result").innerHTML = '<%= j render "users/result.html" %>'

app/views/users/my_portfolio.html.erb
<h1>Stocks</h1>

<%= form_tag search_stock_path, remote: true, method: :get, class: "stock-search" do %>
  <div class="form-group row">
    <div class="col-sm-9 no-right-padding">
      <%= text_field_tag :stock, params[:stock], placeholder: "Stock symbol", autofocus: true, class: "form-control form-control-lg" %>
    </div>
    <div class="col-sm-3 no-left-padding">
      <%= button_tag type: :submit, class: "btn btn-success" do %>
        <%= fa_icon "search 2x" %>
      <% end %>
    </div>
  </div>
<% end %>

<div id="result"></div>

app/views/welcome/index.html.erb
<h1>Index</h1>

<%= link_to "Sign out", destroy_user_session_path, method: :delete %>